sudo: true
language: php
php:
  - 7.2

cache:
  directories:
    - node_modules
    - vendor
    - yarn

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
  - chmod +x ~/docker-compose
  - sudo mv ~/docker-compose /usr/local/bin/docker-compose
  - cp .env.default .env

install:
  - sudo service postgresql stop
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec php make install

before_script:
#  - sudo yarn install
#  - psql -c 'create database coyote_test;' -U postgres
#  - cp tests/acceptance.suite.yml.travis tests/acceptance.suite.yml
#  - php artisan migrate --seed --quiet
  - docker-compose exec php php vendor/bin/codecept build
#  - make file-permission
#  - make assets-production
#  - phantomjs --webdriver=4444 2>&1 >/dev/null &
#  - sleep 5
#  - php -S 127.0.0.1:8000 -t public/ 2>&1 >/dev/null &
#  - php artisan es:create --force
#  - php artisan es:mapping --force
#  - sleep 5

script: docker-compose exec php php vendor/bin/codecept run

after_script:
  - docker-compose stop
  - docker-compose rm -f
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log
  - cat $TRAVIS_BUILD_DIR/tests/_output/*.html
